pipeline {
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages {
        stage('Build') {
            steps {
                sh 'pwd'
                sh 'ls -l'
            }
        }
        stage('Install') {
            steps {
                sh 'pwd'
            }
        }
    }
}
