pipeline {
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages {
        stage('Build') {
            steps {
                sh{
                    'pwd'
                    'cd target'
                    'ls -l'
                    'pwd'
                }
            }
        }
        stage('Install') {
            steps {
                sh 'pwd'
            }
        }
    }
}
